package:
  name: polygon
  version: 0.0.1

source:
  git_url: https://github.com/EUPSForge/polygon.git
  git_tag: v0.0.1

requirements:
  build:
    - python 2.7.*
    - numpy ==1.9
  run:
    - python 2.7.*
    - numpy >=1.9

test:
  # Python imports
  imports:
    - Polygon
    - Polygon.IO
    - Polygon.Shapes
    - Polygon.Utils

about:
  home: https://github.com/EUPSForge/polygon
